
FROM balenalib/raspberry-pi
MAINTAINER ajlennon@dynamicdevices.co.uk

ENV INITSYSTEM on

WORKDIR /usr/src/app

# xterm for 'resize' and ffmpeg for streaming
RUN apt-get update && apt-get install xterm ffmpeg

COPY sleep.sh .
COPY stream.sh .

CMD ["bash", "sleep.sh"]
#CMD ["bash", "stream.sh"]
